routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();
Route::get('/auth/github', ['uses' => 'Auth\AuthController@redirectToGithub', 'as' => 'github.login']);
Route::get('/auth/github/callback', ['uses' => 'Auth\AuthController@handleGithubCallback', 'as' => 'github.callback']);
Route::get('/github/register',['uses' => 'Auth\AuthController@registerFromGithub', 'as' => 'github.register']);
Route::post('/github/store',['uses' => 'Auth\AuthController@store', 'as' => 'github.store']);


Route::get('/', ['uses' => 'HomeController@index', 'as' => 'index']);
Route::get('/about', ['uses' => 'PageController@about', 'as' => 'page.about']);
Route::get('/projects', ['uses' => 'HomeController@projects', 'as' => 'projects']);
Route::get('/search', ['uses' => 'HomeController@search', 'as' => 'search']);

Route::get('/blog', ['uses' => 'PostController@index', 'as' => 'post.index']);
Route::get('/blog/{slug}', ['uses' => 'PostController@show', 'as' => 'post.show']);
Route::get('/category/{name}', ['uses' => 'CategoryController@show', 'as' => 'category.show']);
Route::get('/category', ['uses' => 'CategoryController@index', 'as' => 'category.index']);
Route::get('/tag/{name}', ['uses' => 'TagController@show', 'as' => 'tag.show']);
Route::get('/tag', ['uses' => 'TagController@index', 'as' => 'tag.index']);
Route::get('/user/{name}', ['uses' => 'UserController@show', 'as' => 'user.show']);
Route::patch('/user/upload/avatar', ['uses' => 'UserController@uploadAvatar', 'as' => 'user.upload.avatar']);
Route::patch('/user/upload/profile', ['uses' => 'UserController@uploadProfile', 'as' => 'user.upload.profile']);
Route::patch('/user/upload/info', ['uses' => 'UserController@update', 'as' => 'user.update.info']);


Route::get('/commentable/{commentable_id}/comments', ['uses' => 'CommentController@show', 'as' => 'comment.show']);
Route::resource('comment', 'CommentController', ['only' => ['store', 'destroy', 'edit', 'update']]);


Route::group(['prefix' => 'admin', ['middleware' => ['auth', 'admin']]], function () {

    /**
     * admin url
     */
    Route::get('/', ['uses' => 'AdminController@index', 'as' => 'admin.index']);
    Route::get('/settings', ['uses' => 'AdminController@settings', 'as' => 'admin.settings']);
    Route::post('/settings', ['uses' => 'AdminController@saveSettings', 'as' => 'admin.save-settings']);
    Route::post('/upload/image', ['uses' => 'ImageController@uploadImage', 'as' => 'upload.image']);
    Route::delete('/delete/file', ['uses' => 'FileController@deleteFile', 'as' => 'delete.file']);
    Route::post('/upload/file', ['uses' => 'FileController@uploadFile', 'as' => 'upload.file']);


    /**
     * admin uri
     */
    Route::get('/posts', ['uses' => 'AdminController@posts', 'as' => 'admin.posts']);
    Route::get('/comments', ['uses' => 'AdminController@comments', 'as' => 'admin.comments']);
    Route::get('/tags', ['uses' => 'AdminController@tags', 'as' => 'admin.tags']);
    Route::get('/users', ['uses' => 'AdminController@users', 'as' => 'admin.users']);
    Route::get('/pages', ['uses' => 'AdminController@pages', 'as' => 'admin.pages']);
    Route::get('/categories', ['uses' => 'AdminController@categories', 'as' => 'admin.categories']);
    Route::get('/images', ['uses' => 'ImageController@images', 'as' => 'admin.images']);
    Route::get('/files', ['uses' => 'FileController@files', 'as' => 'admin.files']);

    /**
     * comment
     */
    Route::post('/comment/{comment}/restore', ['uses' => 'CommentController@restore', 'as' => 'comment.restore']);

    /***
     * post
     */

    Route::post('/post/{post}/restore', ['uses' => 'PostController@restore', 'as' => 'post.restore']);
    Route::get('/post/{slug}/preview', ['uses' => 'PostController@preview', 'as' => 'post.preview']);
    Route::post('/post/{post}/publish', ['uses' => 'PostController@publish', 'as' => 'post.publish']);

    /**
     * tag
     */
    Route::delete('/tag/{tag}', ['uses' => 'TagController@destroy', 'as' => 'tag.destroy']);
    Route::post('/tag', ['uses' => 'TagController@store', 'as' => 'tag.store']);

    /**
     * admin resource
     */
    Route::resource('post', 'PostController', ['except' => ['show', 'index']]);
    Route::resource('category', 'CategoryController', ['except' => ['index', 'show', 'create']]);
    Route::resource('page', 'PageController', ['except' => ['show', 'index']]);

});

resources/views/admin/categories.blade.php
@extends('admin.layouts.app')
@section('title','Admin')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="widget widget-default">
                <div class="widget-header">
                    <h3><i class="fa fa-folder fa-fw"></i>分类</h3>
                </div>
                <div class="widget-body">
                    <a class="btn pull-right" role="button" data-toggle="modal" data-target="#add-category-modal">
                        <i class="fa fa-folder-o"></i>
                    </a>
                    <table class="table table-hover table-bordered table-responsive" style="overflow: auto">
                        <thead>
                        <tr>
                            <th>名称</th>
                            <th>日期</th>
                            <th>文章</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($categories as $category)
                            <tr>
                                <td>{{ $category->name }}</td>
                                <td>{{ $category->created_at->format('Y-m-d') }}</td>
                                <td>{{ $category->posts_count }}</td>
                                <td>
                                    <div>
                                        <a href="{{ route('category.edit',$category->id) }}" class="btn btn-info" data-toggle="tooltip" data-placement="top" title="编辑">
                                            <i class="fa fa-pencil fa-fw"></i>
                                        </a>
                                        <button class="btn btn-danger" data-toggle="modal"
                                                data-toggle="tooltip" data-placement="top" title="删除"
                                                data-method="delete"
                                                data-url="{{ route('category.destroy',$category->id) }}"
                                                data-modal-target="{{ $category->name }}">
                                            <i class="fa fa-trash-o fa-fw"></i>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    @include('admin.modals.add-category-modal')
@endsection

resources/views/admin/comments.blade.php
@extends('admin.layouts.app')
@section('title','Admin')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="widget widget-default">
                <div class="widget-header">
                    <h3><i class="fa fa-comments fa-fw"></i>评论</h3>
                </div>
                <div class="widget-body">
                    <table class="table table-hover table-bordered table-responsive">
                        <thead>
                        <tr>
                            <th>用户</th>
                            <th>Email</th>
                            <th>类型</th>
                            <th>内容</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($comments as $comment)
                            <tr class="{{ $comment->trashed() ? 'danger':'' }}">
                                <td>
                                    @if($comment->user_id)
                                        <a href="{{ route('user.show',$comment->username) }}">{{ $comment->username }}</a>
                                    @else
                                        {{ $comment->username }}
                                    @endif
                                </td>
                                <td><a href="mailto:{{ $comment->email }}">{{ $comment->email }}</a></td>
                                <td>{{ $comment->commentable_type }}</td>
                                <td data-toggle="tooltip" data-placement="top"
                                    title="{{ $comment->content }}">{!! $comment->html_content !!}</td>
                                <td>
                                    @if($comment->trashed())
                                        <button type="submit"
                                                class="btn btn-danger"
                                                data-modal-target="这条评论(永久)"
                                                data-url="{{ route('comment.destroy',[$comment->id,'force'=>'true']) }}"
                                                data-method="delete"
                                                data-toggle="tooltip"
                                                data-placement="top"
                                                title="永久删除">
                                            <i class="fa fa-trash-o fa-fw"></i>
                                        </button>
                                        <form style="display: inline-block" method="post" action="{{ route('comment.restore',$comment->id) }}">
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-primary"
                                                    data-toggle="tooltip" data-placement="top" title="恢复">
                                                <i class="fa fa-repeat fa-fw"></i>
                                            </button>
                                        </form>

                                    @else
                                        <button type="submit"
                                                class="btn btn-danger"
                                                data-modal-target="这条评论"
                                                data-url="{{ route('comment.destroy',$comment->id) }}"
                                                data-method="delete"
                                                data-toggle="tooltip"
                                                data-placement="top"
                                                title="删除">
                                            <i class="fa fa-trash-o fa-fw"></i>
                                        </button>
                                        <a class="btn btn-info"
                                           href="{{ route('comment.edit',[$comment->id,'redirect'=>request()->fullUrl()]) }}">
                                            <i class="fa fa-pencil fa-fw"></i>
                                        </a>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $comments->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/files.blade.php
@extends('admin.layouts.app')
@section('title','Admin')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="widget widget-default">
                <div class="widget-header">
                    <h3><i class="fa fa-file fa-fw"></i>文件</h3>
                </div>
                <div class="widget-body">
                    <div class="col-md-12">
                        <div class="col-sm-12">
                            <form role="form" class="form-horizontal" action="{{ route('upload.file') }}"
                                  datatype="image"
                                  enctype="multipart/form-data" method="post">
                                {{ csrf_field() }}
                                <input type="hidden" name="type" value="js">
                                <div class="row">
                                    <div class="form-group col-md-10">
                                        <div class="input-group">
                                            <span class="input-group-addon">Js</span>
                                            <input class="form-control" type="file" name="file">
                                        </div>
                                    </div>
                                    <div class="form-group col-md-2">
                                        <button type="submit" class="btn btn-primary" style="margin-left: 5px">
                                            上传
                                        </button>
                                    </div>
                                </div>
                            </form>



                            <form role="form" class="form-horizontal" action="{{ route('upload.file') }}"
                                  datatype="image"
                                  enctype="multipart/form-data" method="post">
                                {{ csrf_field() }}
                                <input type="hidden" name="type" value="css">
                                <div class="row">
                                    <div class="form-group col-md-10">
                                        <div class="input-group">
                                            <span class="input-group-addon">Css</span>
                                            <input class="form-control" type="file" name="file">
                                        </div>
                                    </div>
                                    <div class="form-group col-md-2">
                                        <button type="submit" class="btn btn-primary" style="margin-left: 5px">
                                            上传
                                        </button>
                                    </div>
                                </div>
                            </form>



                            <form role="form" class="form-horizontal" action="{{ route('upload.file') }}"
                                  datatype="image"
                                  enctype="multipart/form-data" method="post">
                                {{ csrf_field() }}
                                <input type="hidden" name="type" value="font">
                                <div class="row">
                                    <div class="form-group col-md-10">
                                        <div class="input-group">
                                            <span class="input-group-addon">Font</span>
                                            <input class="form-control" type="file" name="file">
                                        </div>
                                    </div>
                                    <div class="form-group col-md-2">
                                        <button type="submit" class="btn btn-primary" style="margin-left: 5px">
                                            上传
                                        </button>
                                    </div>
                                </div>
                            </form>




                        </div>
                    </div>
                    <table class="table table-hover table-bordered table-responsive">
                        <tbody>
                        @forelse($files as $file)
                            <tr>
                                <td>{{ $file->type }}</td>
                                <td>{{ getUrlByFileName($file->key) }}</td>
                                <td>
                                    <button id="clipboard-btn" class="btn btn-default"
                                            type="button"
                                            data-clipboard-text="{{ getUrlByFileName($file->key) }}"
                                            data-toggle="tooltip"
                                            data-placement="left"
                                            title="Copied">
                                        <i class="fa fa-copy fa-fw"></i>
                                    </button>
                                    <button class="btn btn-danger"
                                            data-method="delete"
                                            data-modal-target="{{ $file->key }}"
                                            data-url="{{ route('delete.file').'?key='.$file->key."&type=".$file->type }}">
                                        <i class="fa fa-trash-o fa-fw"></i>
                                    </button>
                                </td>
                            </tr>
                        @empty
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="//cdn.bootcss.com/clipboard.js/1.5.12/clipboard.min.js"></script>
    <script>
        new Clipboard('.btn');
        $('.btn').tooltip({
            trigger: 'click',
        });
    </script>
@endsection

resources/views/admin/images.blade.php
@extends('admin.layouts.app')
@section('title','Admin')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="widget widget-default">
                <div class="widget-header">
                    <h3><i class="fa fa-file-image-o fa-fw"></i>图片({{ $image_count }})</h3>
                </div>
                <div class="widget-body">
                    <div class="col-md-12">
                        <form role="form" class="form-horizontal" action="{{ route('upload.image') }}"
                              datatype="image"
                              required=""
                              enctype="multipart/form-data" method="post">
                            {{ csrf_field() }}
                            <div class="row">
                                <div class="form-group col-md-10">
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-file-image-o  fa-fw"></i></span>
                                        <input class="form-control" accept="image/*" type="file" name="image">
                                    </div>
                                </div>
                                <div class="form-group col-md-2">
                                    <button type="submit" class="btn btn-primary" style="margin-left: 5px">
                                        上传
                                    </button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        @forelse($images as $image)
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <div class="widget widget-default">
                    <img src="{{ getUrlByFileName($image->key) }}" style="width: 100% ;height: 200px">
                    <div class="widget-footer">
                        <div class="widget-meta">
                            <button id="clipboard-btn" class="btn btn-default"
                                    type="button"
                                    data-clipboard-text="{{ getUrlByFileName($image->key) }}"
                                    data-toggle="tooltip"
                                    data-placement="left"
                                    title="Copied">
                                <i class="fa fa-copy fa-fw"></i>
                            </button>
                            <button class="btn btn-danger"
                                    data-method="delete"
                                    data-modal-target="{{ $image->key }}"
                                    data-url="{{ route('delete.file').'?key='.$image->key.'&type=image' }}"
                                    data-key="{{ $image->key }}">
                                <i class="fa fa-trash-o fa-fw"></i>
                            </button>
                            {{ formatBytes($image->size) }}
                            <i class="fa fa-clock-o fa-fw"></i>
                            {{ $image->created_at->format('Y-m-d H:m') }}
                        </div>
                    </div>
                </div>
            </div>
        @empty
            <h3 class="center-block meta-item">没有图片</h3>
        @endforelse
    </div>
    @if($images->lastPage() > 1)
        <div class="row">
            <div class="col-md-12">
                {{ $images->links() }}
            </div>
        </div>
    @endif
@endsection
@section('script')
    <script src="//cdn.bootcss.com/clipboard.js/1.5.12/clipboard.min.js"></script>
    <script>
        new Clipboard('.btn');
        $('.btn').tooltip({
            trigger: 'click',
        });
    </script>
@endsection

resources/views/admin/pages.blade.php
@extends('admin.layouts.app')
@section('title','Admin')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="widget widget-default">
                <div class="widget-header">
                    <h3><i class="fa fa-file fa-fw"></i>页面</h3>
                </div>
                <div class="widget-body">
                    <a class="btn pull-right" href="{{ route('page.create') }}">
                        <i class="fa fa-file"></i>
                    </a>
                    <table class="table table-hover table-bordered table-responsive">
                        <thead>
                        <tr>
                            <th>名称</th>
                            <th>url</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($pages as $page)
                            <tr>
                                <td>{{ $page->display_name }}</td>
                                <td>/{{ $page->name }}</td>
                                <td>
                                    <div>

                                        <a href="{{ route('page.edit',$page->id) }}"
                                           data-toggle="tooltip" data-placement="top" title="编辑"
                                           class="btn btn-info">
                                            <i class="fa fa-pencil fa-fw"></i>
                                        </a>
                                        <a href="/{{ $page->name }}"
                                           data-toggle="tooltip" data-placement="top" title="查看"
                                           class="btn btn-success">
                                            <i class="fa fa-eye fa-fw"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/posts.blade.php
@extends('admin.layouts.app')
@section('title','Admin')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="widget widget-default">
                <div class="widget-header">
                    <h3><i class="fa fa-sticky-note fa-fw"></i>文章</h3>
                </div>
                <div class="widget-body">
                    <table class="table table-hover table-bordered table-responsive">
                        <thead>
                        <tr>
                            <th>标题</th>
                            <th>状态</th>
                            {{--<th>slug</th>--}}
                            <th>action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($posts as $post)
                            <?php
                            $class = '';
                            $status = 'Un published';
                            if ($post->trashed()) {
                                $class = 'danger';
                                $status = 'Deleted';
                            } else if ($post->isPublished()) {
                                $class = 'success';
                                $status = 'Published';
                            }
                            ?>
                            <tr class="{{ $class }}">
                                <td>{{ $post->title }}</td>
                                <td>{{ $status }}</td>
                                {{--<td>{{ $post->slug }}</td>--}}
                                <td>
                                    <div>
                                        <a {{ $post->trashed()?'disabled':'' }} href="{{ $post->trashed()?'javascript:void(0)':route('post.edit',$post->id) }}"
                                           data-toggle="tooltip" data-placement="top" title="编辑"
                                           class="btn btn-info">
                                            <i class="fa fa-pencil fa-fw"></i>
                                        </a>
                                        @if($post->trashed())
                                            <form style="display: inline" method="post" action="{{ route('post.restore',$post->id) }}">
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="恢复">
                                                    <i class="fa fa-repeat fa-fw"></i>
                                                </button>
                                            </form>

                                        @elseif($post->isPublished())
                                            <a href="{{ route('post.show',$post->slug) }}"
                                               data-toggle="tooltip" data-placement="top" title="查看"
                                               class="btn btn-success">
                                                <i class="fa fa-eye fa-fw"></i>
                                            </a>
                                            <form style="display: inline" method="post" action="{{ route('post.publish',$post->id) }}">
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-warning" data-toggle="tooltip" data-placement="top" title="撤销发布">
                                                    <i class="fa fa-undo fa-fw"></i>
                                                </button>
                                            </form>
                                        @else
                                            <a href="{{ route('post.preview',$post->slug) }}"  data-toggle="tooltip" data-placement="top" title="预览"
                                               class="btn btn-default">
                                                <i class="fa fa-eye fa-fw"></i>
                                            </a>
                                            <form style="display: inline" method="post" action="{{ route('post.publish',$post->id) }}">
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="发布">
                                                    <i class="fa fa-send-o fa-fw"></i>
                                                </button>
                                            </form>
                                        @endif
                                        <button class="btn btn-danger" data-toggle="modal" data-title="{{ $post->title }}"
                                                data-toggle="tooltip" data-placement="top" title="删除"
                                                data-url="{{ route('post.destroy',$post->id) }}"
                                                data-force="{{ $post->trashed() }}"
                                                data-target="#delete-post-modal">
                                            <i class="fa fa-trash-o  fa-fw"></i>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $posts->links() }}
                </div>
            </div>
        </div>
    </div>
    {{-- modal --}}
    <div class="modal fade" id="delete-post-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">删除</h4>
                </div>
                <div class="modal-body">
                    确定删除<span id="span-title"></span>吗?
                </div>
                <div class="modal-footer">
                    <form id="delete-form" method="post">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="redirect" value="/admin/posts">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <button id="confirm-btn" type="submit" class="btn btn-primary">确定</button>
                    </form>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
@endsection

@section('script')
    <script>
        $('#delete-post-modal').on('show.bs.modal', function (e) {
            var url = $(e.relatedTarget).data('url');
            var title = $(e.relatedTarget).data('title');
            var force = $(e.relatedTarget).data('force');
            if (force == '1')
            {
                $('#confirm-btn').text('确定(这将永久刪除)');
                $('#confirm-btn').attr('class','btn btn-danger');
            }
            $('#span-title').text(title);
            $('#delete-form').attr('action', url);
        });
    </script>
@endsection