routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();
Route::get('/auth/github', ['uses' => 'Auth\AuthController@redirectToGithub', 'as' => 'github.login']);
Route::get('/auth/github/callback', ['uses' => 'Auth\AuthController@handleGithubCallback', 'as' => 'github.callback']);
Route::get('/github/register',['uses' => 'Auth\AuthController@registerFromGithub', 'as' => 'github.register']);
Route::post('/github/store',['uses' => 'Auth\AuthController@store', 'as' => 'github.store']);


Route::get('/', ['uses' => 'HomeController@index', 'as' => 'index']);
Route::get('/about', ['uses' => 'PageController@about', 'as' => 'page.about']);
Route::get('/projects', ['uses' => 'HomeController@projects', 'as' => 'projects']);
Route::get('/search', ['uses' => 'HomeController@search', 'as' => 'search']);

Route::get('/blog', ['uses' => 'PostController@index', 'as' => 'post.index']);
Route::get('/blog/{slug}', ['uses' => 'PostController@show', 'as' => 'post.show']);
Route::get('/category/{name}', ['uses' => 'CategoryController@show', 'as' => 'category.show']);
Route::get('/category', ['uses' => 'CategoryController@index', 'as' => 'category.index']);
Route::get('/tag/{name}', ['uses' => 'TagController@show', 'as' => 'tag.show']);
Route::get('/tag', ['uses' => 'TagController@index', 'as' => 'tag.index']);
Route::get('/user/{name}', ['uses' => 'UserController@show', 'as' => 'user.show']);
Route::patch('/user/upload/avatar', ['uses' => 'UserController@uploadAvatar', 'as' => 'user.upload.avatar']);
Route::patch('/user/upload/profile', ['uses' => 'UserController@uploadProfile', 'as' => 'user.upload.profile']);
Route::patch('/user/upload/info', ['uses' => 'UserController@update', 'as' => 'user.update.info']);


Route::get('/commentable/{commentable_id}/comments', ['uses' => 'CommentController@show', 'as' => 'comment.show']);
Route::resource('comment', 'CommentController', ['only' => ['store', 'destroy', 'edit', 'update']]);


Route::group(['prefix' => 'admin', ['middleware' => ['auth', 'admin']]], function () {

    /**
     * admin url
     */
    Route::get('/', ['uses' => 'AdminController@index', 'as' => 'admin.index']);
    Route::get('/settings', ['uses' => 'AdminController@settings', 'as' => 'admin.settings']);
    Route::post('/settings', ['uses' => 'AdminController@saveSettings', 'as' => 'admin.save-settings']);
    Route::post('/upload/image', ['uses' => 'ImageController@uploadImage', 'as' => 'upload.image']);
    Route::delete('/delete/file', ['uses' => 'FileController@deleteFile', 'as' => 'delete.file']);
    Route::post('/upload/file', ['uses' => 'FileController@uploadFile', 'as' => 'upload.file']);


    /**
     * admin uri
     */
    Route::get('/posts', ['uses' => 'AdminController@posts', 'as' => 'admin.posts']);
    Route::get('/comments', ['uses' => 'AdminController@comments', 'as' => 'admin.comments']);
    Route::get('/tags', ['uses' => 'AdminController@tags', 'as' => 'admin.tags']);
    Route::get('/users', ['uses' => 'AdminController@users', 'as' => 'admin.users']);
    Route::get('/pages', ['uses' => 'AdminController@pages', 'as' => 'admin.pages']);
    Route::get('/categories', ['uses' => 'AdminController@categories', 'as' => 'admin.categories']);
    Route::get('/images', ['uses' => 'ImageController@images', 'as' => 'admin.images']);
    Route::get('/files', ['uses' => 'FileController@files', 'as' => 'admin.files']);

    /**
     * comment
     */
    Route::post('/comment/{comment}/restore', ['uses' => 'CommentController@restore', 'as' => 'comment.restore']);

    /***
     * post
     */

    Route::post('/post/{post}/restore', ['uses' => 'PostController@restore', 'as' => 'post.restore']);
    Route::get('/post/{slug}/preview', ['uses' => 'PostController@preview', 'as' => 'post.preview']);
    Route::post('/post/{post}/publish', ['uses' => 'PostController@publish', 'as' => 'post.publish']);

    /**
     * tag
     */
    Route::delete('/tag/{tag}', ['uses' => 'TagController@destroy', 'as' => 'tag.destroy']);
    Route::post('/tag', ['uses' => 'TagController@store', 'as' => 'tag.store']);

    /**
     * admin resource
     */
    Route::resource('post', 'PostController', ['except' => ['show', 'index']]);
    Route::resource('category', 'CategoryController', ['except' => ['index', 'show', 'create']]);
    Route::resource('page', 'PageController', ['except' => ['show', 'index']]);

});

resources/views/widget/categories.blade.php
<div class="widget widget-default">
    <div class="widget-header"><h4><i class="fa fa-folder fa-fw"></i>分类</h4></div>
    <ul class="widget-body list-group">
        @forelse($categories as $category)
            @if(str_contains(urldecode(request()->getPathInfo()),'category/'.$category->name))
                <li href="{{ route('category.show',$category->name) }}"
                    class="list-group-item active">
                    {{ $category->name }}
                    <span class="badge">{{ $category->posts_count }}</span>
                </li>
            @else
                <a href="{{ route('category.show',$category->name) }}"
                   class="list-group-item">
                    {{ $category->name }}
                    <span class="badge">{{ $category->posts_count }}</span>
                </a>
            @endif
        @empty
            <p class="meta-item center-block">No categories.</p>
        @endforelse
    </ul>
</div>

resources/views/widget/comment.blade.php
<div class="widget widget-default">
    <div class="widget-header">
        <h4 id="comments_count">评论{{--({{ $commentable->comments_count }})--}}</h4>
    </div>
    <div class="widget-body">
        <div id="comments-container"
             data-api-url="{{ route('comment.show',[$commentable->id,
             'commentable_type'=>$commentable_type,
             'redirect'=>(isset($redirect) && $redirect ? $redirect:'')]) }}">
        </div>
        <form id="comment-form" method="post" action="{{ route('comment.store') }}">
            {{ csrf_field() }}
            <input type="hidden" name="commentable_id" value="{{ $commentable->id }}">
            <input type="hidden" name="commentable_type" value="{{ $commentable_type }}">
            @if(!auth()->check())
                <div class="form-group">
                    <label for="username">姓名<span class="required">*</span></label>
                    <input class="form-control" id="username" type="text" name="username" placeholder="您的大名">
                </div>
                <div class="form-group">
                    <label for="email">邮箱<span class="required">*</span></label>
                    <input class="form-control" id="email" type="email" name="email" placeholder="邮箱不会公开">
                </div>
            @endif
            <div class="form-group">
                <label for="comment-content">评论内容<span class="required">*</span></label>
                <textarea placeholder="支持Markdown" style="resize: vertical" id="comment-content" name="content"
                          rows="5" spellcheck="false" class="form-control markdown-content autosize-target"></textarea>
                <span class="help-block required">
                    <strong id="comment_error_msg"></strong>
                </span>
            </div>
            <div class="form-group">
                <input type="submit" id="comment-submit" class="btn btn-primary"
                       value="回复"/>
            </div>
        </form>
    </div>
</div>

resources/views/widget/google_analytics.blade.php
@if(!isAdmin(Auth::user()) && isset($google_analytics) && $google_analytics == 'true')
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', '{{ $google_trace_id or '' }}', 'auto');
        ga('send', 'pageview');
    </script>
@endif

resources/views/widget/tags.blade.php
<div class="widget widget-default">
    <div class="widget-header"><h4><i class="fa fa-tags fa-fw"></i>标签</h4></div>
    <ul class="widget-body">
        <div class="tag-list">
            @forelse($tags as $tag)
                @if(str_contains(urldecode(request()->getPathInfo()),'tag/'.$tag->name))
                    <span class="tag tag-active">
                        {{ $tag->name }}
                        <span class="badge badge-active">{{ $tag->posts_count }}</span>
                    </span>
                @else
                    <a href="{{ route('tag.show',$tag->name) }}" class="tag">
                        {{ $tag->name }}
                        <span class="badge">{{ $tag->posts_count }}</span>
                    </a>
                @endif
            @empty <p class="meta-item center-block">No tags.</p>
            @endforelse
        </div>
    </ul>
</div>

resources/views/widget/user.blade.php
<div class="widget widget-user" style="overflow: hidden">
    <?php
    if (isset($profile_image) && $profile_image)
        $style = "background: url($profile_image) center center;";
    else
        $style = "background-color: #607D8B;";
    ?>
    <div class="widget-user-header" style="{{ $style }}">
        <h3 class="widget-user-username">lufficc</h3>
        <h5 class="widget-user-desc">{{ $description or 'description' }}</h5>
    </div>
    <div class="widget-user-image">
        <img class="img-circle" src="{{ $avatar or 'https://avatars0.githubusercontent.com/u/20706332?v=3&s=466' }}" alt="User Avatar">
    </div>
    <div class="widget-user-footer">
        <div class="row">
            <div class="col-sm-3 border-right">
                <div class="description-block">
                    <a href="{{ config('social.weibo') }}" class="description-header"><i class="fa fa-weibo fa-lg"
                                                                                         aria-hidden="true"></i></a>
                </div>
            </div>
            <div class="col-sm-3 border-right">
                <div class="description-block">
                    <a href="{{ config('social.github') }}" class="description-header fa-lg"><i
                                class="fa fa-github fa-lg" aria-hidden="true"></i></a>
                </div>
            </div>
            <div class="col-sm-3 border-right">
                <div class="description-block">
                    <a href="{{ config('social.facebook') }}" class="description-header"><i
                                class="fa fa-facebook-official fa-lg"
                                aria-hidden="true"></i></a>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="description-block">
                    <a href="{{ config('social.twitter') }}" class="description-header"><i class="fa fa-twitter fa-lg"
                                                                                           aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>